name: Webless CI

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - run: shards install
      - run: crystal tool format --check
      - run: ./bin/ameba
  specs:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            crystal: latest
          - os: windows-latest
            crystal: latest
          - os: macos-latest
            crystal: latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - run: shards install--skip-executables --skip-postinstall
      - run: crystal spec
